Dissolved Oxygen:
  attributes:
    _FillValue:
      type: float
      value: NaN
    colorBarMaximum:
      type: double
      value: '1.0'
    colorBarMinimum:
      type: double
      value: '0.0'
    ioos_category:
      value: Dissolved O2
    long_name:
      value: Volume Fraction Of Oxygen In Sea Water
    standard_name:
      value: volume_fraction_of_oxygen_in_sea_water
    units:
      value: '% saturation'
  dataType: float
  destinationName: Dissolved_Oxygen
Dissolved Oxygen_mg/L:
  attributes:
    ioos_category:
      value: Dissolved Oxygen
    long_name:
      value: Dissolved Oxygen
    units:
      value: mg/L
  dataType: float
  destinationName: Dissolved Oxygen_mg/L
Dissolved Oxygen_nan:
  attributes:
    ioos_category:
      value: Dissolved Oxygen
    long_name:
      value: Dissolved Oxygen
    units:
      value: nan
  dataType: float
  destinationName: Dissolved Oxygen_nan
Dissolved Oxygen_percent saturation:
  attributes:
    ioos_category:
      value: Dissolved Oxygen
    long_name:
      value: Dissolved Oxygen
    units:
      value: percent saturation
  dataType: float
  destinationName: Dissolved Oxygen_percent saturation
Salinity:
  attributes:
    ioos_category:
      value: Salinity
    long_name:
      value: Volume Fraction Of Salinity In Sea Water
    units:
      value: practical salinity units
  dataType: float
  destinationName: Salinity
Salinity_nan:
  attributes:
    ioos_category:
      value: Salinity
    long_name:
      value: Salinity
    units:
      value: nan
  dataType: float
  destinationName: Salinity_nan
Salinity_practical salinity units:
  attributes:
    ioos_category:
      value: Salinity
    long_name:
      value: Salinity
    units:
      value: practical salinity units
  dataType: float
  destinationName: Salinity_practical salinity units
Temperature:
  attributes:
    _FillValue:
      type: float
      value: NaN
    ioos_category:
      value: Temperature
    long_name:
      value: Temperature
    units:
      value: degrees Celsius
  dataType: float
  destinationName: Temperature
Temperature_degrees Celsius:
  attributes:
    ioos_category:
      value: Temperature
    long_name:
      value: Temperature
    units:
      value: degrees Celsius
  dataType: float
  destinationName: Temperature_degrees Celsius
Temperature_nan:
  attributes:
    ioos_category:
      value: Temperature
    long_name:
      value: Temperature
    units:
      value: nan
  dataType: float
  destinationName: Temperature_nan
deployment_end_date:
  attributes:
    ioos_category:
      value: Time
    long_name:
      value: Deployment End Date
    source_name:
      value: deployment_end_date
    time_precision:
      value: '1970-01-01'
    units:
      value: yyyy-MM-dd
  dataType: String
  destinationName: deployment_end_date
deployment_period:
  attributes:
    ioos_category:
      value: Unknown
    long_name:
      value: Deployment Period
  dataType: String
  destinationName: deployment_period
deployment_start_date:
  attributes:
    ioos_category:
      value: Time
    long_name:
      value: Deployment Start Date
    source_name:
      value: deployment_start_date
    time_precision:
      value: '1970-01-01'
    units:
      value: yyyy-MM-dd
  dataType: String
  destinationName: deployment_start_date
depth:
  attributes:
    colorBarMaximum:
      type: double
      value: '8000.0'
    colorBarMinimum:
      type: double
      value: '-8000.0'
    colorBarPalette:
      value: TopographyDepth
    ioos_category:
      value: Location
    long_name:
      value: Depth
    standard_name:
      value: depth
    units:
      value: m
  dataType: byte
  destinationName: depth
depth_crosscheck_flag:
  attributes:
    ancillary_variables:
      value: sensor_depth_at_low_tide_m
    ioos_category:
      value: Quality
    long_name:
      value: Depth Crosscheck Flag
    standard_name:
      value: quality_flag
  dataType: String
  destinationName: depth_crosscheck_flag
dissolved_oxygen_percent_saturation:
  attributes:
    ioos_category:
      value: Dissolved O2
    long_name:
      value: Volume Fraction Of Oxygen In Sea Water
    standard_name:
      value: volume_fraction_of_oxygen_in_sea_water
    units:
      value: '% saturation'
  dataType: float
  destinationName: dissolved_oxygen
dissolved_oxygen_uncorrected_mg_per_l:
  attributes:
    ioos_category:
      value: Dissolved O2
    long_name:
      value: Mass Concentration of Oxygen in Sea Water
    standard_name:
      value: mass_concentration_of_oxygen_in_sea_water
    units:
      value: mg/L
  dataType: float
  destinationName: dissolved_oxygen_uncorrected
latitude:
  attributes:
    colorBarMaximum:
      type: double
      value: '90.0'
    colorBarMinimum:
      type: double
      value: '-90.0'
    ioos_category:
      value: Location
    long_name:
      value: Latitude
    standard_name:
      value: latitude
    units:
      value: degrees_north
  dataType: float
  destinationName: latitude
lease:
  attributes:
    ioos_category:
      value: Unknown
    long_name:
      value: Lease
  dataType: String
  destinationName: lease
lease_number:
  attributes:
    ioos_category:
      value: Unknown
    long_name:
      value: Lease Number
  dataType: String
  destinationName: lease_number
longitude:
  attributes:
    colorBarMaximum:
      type: double
      value: '180.0'
    colorBarMinimum:
      type: double
      value: '-190.0'
    ioos_category:
      value: Location
    long_name:
      value: Longitude
    standard_name:
      value: longitude
    units:
      value: degrees_east
  dataType: float
  destinationName: longitude
measured_sensor_depth_m:
  attributes:
    ioos_category:
      value: Location
    long_name:
      value: Measured Sensor Depth
    units:
      value: m
  dataType: float
  destinationName: measured_sensor_depth
mooring:
  attributes:
    ioos_category:
      value: ''
    long_name:
      value: ''
  dataType: ''
  destinationName: ''
qc_flag_dissolved_oxygen_percent_saturation:
  attributes:
    ancillary_variables:
      value: dissolved_oxygen_percent_saturation
    ioos_category:
      value: Quality
    long_name:
      value: 'Quality Flag for Parameter: Dissolved Oxygen (Percent Saturation)'
    standard_name:
      value: quality_flag
  dataType: String
  destinationName: qc_flag_dissolved_oxygen
qc_flag_dissolved_oxygen_uncorrected_mg_per_l:
  attributes:
    ancillary_variables:
      value: dissolved_oxygen_uncorrected_mg_per_l
    ioos_category:
      value: Quality
    long_name:
      value: 'Quality Flag for Parameter: Dissolved Oxygen Uncorrected (mg/L)'
    standard_name:
      value: quality_flag
  dataType: String
  destinationName: qc_flag_dissolved_oxygen_uncorrected
qc_flag_salinity_psu:
  attributes:
    ancillary_variables:
      value: salinity_psu
    ioos_category:
      value: Quality
    long_name:
      value: 'Quality Flag for Parameter: Salinity (PSU)'
    standard_name:
      value: quality_flag
  dataType: String
  destinationName: qc_flag_salinity
qc_flag_sensor_depth_measured_m:
  attributes:
    ancillary_variables:
      value: sensor_depth_measured_m
    ioos_category:
      value: Quality
    long_name:
      value: 'Quality Flag for Parameter: Sensor Depth Measured (m)'
    standard_name:
      value: quality_flag
  dataType: String
  destinationName: qc_flag_sensor_depth_measured
qc_flag_temperature_degree_c:
  attributes:
    ancillary_variables:
      value: temperature_degree_c
    ioos_category:
      value: Quality
    long_name:
      value: 'Quality Flag for Parameter: Temperature (Degree Celsius)'
    standard_name:
      value: quality_flag
  dataType: String
  destinationName: qc_flag_temperature
salinity_psu:
  attributes:
    ioos_category:
      value: Salinity
    long_name:
      value: Salinity
    units:
      value: PSU
  dataType: float
  destinationName: salinity
sensor:
  attributes:
    ioos_category:
      value: Unknown
    long_name:
      value: Sensor
  dataType: String
  destinationName: sensor
sensor_depth_at_low_tide_m:
  attributes:
    colorBarMaximum:
      type: double
      value: '8000.0'
    colorBarMinimum:
      type: double
      value: '-8000.0'
    colorBarPalette:
      value: TopographyDepth
    ioos_category:
      value: Location
    long_name:
      value: Sensor depth at low tide
    standard_name:
      value: depth
    units:
      value: m
  dataType: float
  destinationName: depth
sensor_depth_measured_m:
  attributes:
    colorBarMaximum:
      type: double
      value: '8000.0'
    colorBarMinimum:
      type: double
      value: '-8000.0'
    ioos_category:
      value: Location
    long_name:
      value: Depth measured by sensor
    units:
      value: m
  dataType: float
  destinationName: sensor_depth_measured
sensor_serial_number:
  attributes:
    ioos_category:
      value: Unknown
    long_name:
      value: Sensor Serial Number
  dataType: String
  destinationName: sensor_serial_number
sensor_type:
  attributes:
    ioos_category:
      value: Unknown
    long_name:
      value: Sensor Type
  dataType: String
  destinationName: sensor_type
station:
  attributes:
    cf_role:
      value: timeseries_id
    ioos_category:
      value: Identifier
    long_name:
      value: Station
  dataType: String
  destinationName: station
string_configuration:
  attributes:
    ioos_category:
      value: Unknown
    long_name:
      value: String Configuration
  dataType: String
  destinationName: string_configuration
temperature_degree_c:
  attributes:
    _FillValue:
      type: float
      value: NaN
    ioos_category:
      value: Temperature
    long_name:
      value: Sea Water Temperature
    standard_name:
      value: sea_water_temperature
    units:
      value: degrees_Celsius
  dataType: float
  destinationName: temperature
timestamp:
  attributes:
    ioos_category:
      value: Time
    long_name:
      value: Timestamp
    source_name:
      value: timestamp
    standard_name:
      value: time
    time_precision:
      value: '1970-01-01T00:00:00Z'
    units:
      value: yyyy-MM-dd'T'HH:mm:ss.SSS
  dataType: String
  destinationName: time
timestamp_utc:
  attributes:
    ioos_category:
      value: Time
    long_name:
      value: Timestamp
    source_name:
      value: timestamp_utc
    standard_name:
      value: time
    time_precision:
      value: '1970-01-01T00:00:00Z'
    units:
      value: yyyy-MM-dd'T'HH:mm:ss
  dataType: String
  destinationName: time
waterbody:
  attributes:
    ioos_category:
      value: Unknown
    long_name:
      value: Waterbody
  dataType: String
  destinationName: waterbody
waterbody_station:
  attributes:
    ioos_category:
      value: Unknown
    long_name:
      value: Waterbody
  dataType: String
  destinationName: waterbody_station
